---
services:
  celery_worker:
    container_name: weather-monorepo_celery_worker
    restart: unless-stopped
    build:
      context: ..
      args:
        PYTHON_BASE_IMG: 3.11-slim
      dockerfile: containers/celery.Dockerfile
      target: celery_worker
    env_file: .env
    # volumes:
    #   - ../apps:/project/apps
    #   - ../packages:/project/packages
    #   - ../scripts:/project/scripts
    #   - ../shared:/project/shared
    environment:
      LOG_LEVEL: ${CELERY_WORKER_LOG_LEVEL:-INFO}
      WEATHERAPI_API_KEY: ${WEATHERAPI_API_KEY}
      WEATHERAPI_LOCATION: ${WEATHERAPI_API_LOCATION:-London}

      CELERY_BROKER_HOST: ${CELERY_HOST:-localhost}
      CELERY_BROKER_PORT: ${RABBITMQ_MAIN_PORT:-5672}
      CELERY_BROKER_USER: ${RABBITMQ_USER:-rabbitmq}
      CELERY_BROKER_PASSSWORD: ${RABBITMQ_PASSWORD:-rabbitmq}

      CELERY_BACKEND_HOST: ${CELERY_BACKEND_HOST:-localhost}
      CELERY_BACKEND_PORT: ${REDIS_PORT:-6379}

      CELERY_WORKER_LOG_LEVEL: ${CELERY_WORKER_LOG_LEVEL:-INFO}
      CELERY_WORKER_UID: ${CELERY_WORKER_GID:-0}
      CELERY_WORKER_GID: ${CELERY_WORKER_GID:-0}

      CELERY_BEAT_LOG_LEVEL: ${CELERY_BEAT_LOG_LEVEL:-INFO}
      CELERY_TZ: ${CELERY_TZ:-Etc/UTC}
