[project]
name = "weatherapi-client"
version = "0.1.0"
description = "Default template for PDM package"
authors = [{ name = "redjax", email = "none@none.com" }]
dependencies = [
    "dynaconf>=3.2.6",
    "core @ file:///${PROJECT_ROOT}/../core",
    "http-lib @ file:///${PROJECT_ROOT}/../http-lib",
    "pydantic>=2.9.2",
    "alembic>=1.13.3",
    "psycopg2-binary>=2.9.9",
    "sqlalchemy>=2.0.35",
]
requires-python = "==3.11.*"
readme = "README.md"
license = { text = "MIT" }

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
