[default]

log_level = "INFO"
log_fmt = "%(asctime)s | [%(levelname)s] | (%(name)s) > %(module)s.%(funcName)s:%(lineno)s |> %(message)s"
log_datefmt = "%Y-%m-%d_%H-%M-%S"
log_silence_loggers = ["httpx", "hishel", "httpcore"]

[logging]

log_level = "INFO"
log_silence_loggers = ["httpx", "hishel", "httpcore"]
